### ISSUE TITLE
请教各个参数哪里设置的

### ISSUE THREAD

**Issue by yylaji** [hkmayfly/JDG#1]

**Comment by hkmayfly** [comment]
在代码里面，按照我写的这个教程：https://www.cnblogs.com/Mayfly-nymph/p/12333524.html

**Comment by yylaji** [comment]
谢谢哥，做的太好了，要是可以京东和京东健康预约抢购就无敌了

**Comment by hkmayfly** [comment]
> 谢谢哥，做的太好了，要是可以京东和京东健康预约抢购就无敌了

谢谢支持！能够帮到你就行。预约抢购功能后面会考虑加进去。
